# For more details on how to configure Wrangler, refer to:
# https://developers.cloudflare.com/workers/wrangler/configuration/

name = "gallery"
main = ".svelte-kit/cloudflare/_worker.js"
compatibility_date = "2026-01-03"
compatibility_flags = [ "nodejs_als" ]

[assets]
binding = "ASSETS"
directory = ".svelte-kit/cloudflare"
